// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"lyrics-server/internal/config"
	"lyrics-server/internal/dao"
	"lyrics-server/internal/handler"
	"lyrics-server/internal/provider/dictionary"
	"lyrics-server/internal/provider/lyrics"
	"lyrics-server/internal/provider/pronunciation"
	"lyrics-server/internal/provider/tokenizer"
	"lyrics-server/internal/provider/translation"
	"lyrics-server/internal/router"
	"lyrics-server/internal/service"
)

// Injectors from wire.go:

// InitializeApp 由 wire 生成 wire_gen.go 中的实现。
func InitializeApp(cfg *config.Config) (*App, error) {
	healthHandler := handler.NewHealthHandler()
	db, err := dao.NewDB(cfg)
	if err != nil {
		return nil, err
	}
	lyricDaoGorm := dao.NewLyricDao(db)
	settingsService := service.NewSettingsService(cfg)
	youdaoTranslationProvider := translation.NewYoudaoTranslationProvider(settingsService)
	myMemoryTranslationProvider := translation.NewMyMemoryTranslationProvider()
	compositeTranslationProvider := translation.NewCompositeTranslationProvider(youdaoTranslationProvider, myMemoryTranslationProvider)
	englishTokenizer := tokenizer.NewEnglishTokenizer()
	japaneseTokenizer, err := tokenizer.NewJapaneseTokenizer()
	if err != nil {
		return nil, err
	}
	compositeTokenizer := tokenizer.NewCompositeTokenizer(englishTokenizer, japaneseTokenizer)
	neteaseCloudMusicApiProvider := lyrics.NewNeteaseCloudMusicApiProvider()
	lyricService := service.NewLyricService(lyricDaoGorm, compositeTranslationProvider, compositeTokenizer, neteaseCloudMusicApiProvider, cfg)
	lyricHandler := handler.NewLyricHandler(lyricService)
	wordDaoGorm := dao.NewWordDao(db)
	freeDictionaryProvider := dictionary.NewFreeDictionaryProvider()
	jishoDictionaryProvider := dictionary.NewJishoDictionaryProvider()
	compositeDictionaryProvider := dictionary.NewCompositeDictionaryProvider(freeDictionaryProvider, jishoDictionaryProvider)
	youdaoDictVoiceProvider := pronunciation.NewYoudaoDictVoiceProvider()
	wordService := service.NewWordService(wordDaoGorm, compositeDictionaryProvider, compositeTokenizer, youdaoDictVoiceProvider, compositeTranslationProvider, cfg)
	wordHandler := handler.NewWordHandler(wordService)
	vocabularyService := service.NewVocabularyService(wordDaoGorm)
	vocabularyHandler := handler.NewVocabularyHandler(vocabularyService)
	songHandler := handler.NewSongHandler(lyricService)
	settingsHandler := handler.NewSettingsHandler(settingsService)
	engine := router.NewRouter(healthHandler, lyricHandler, wordHandler, vocabularyHandler, songHandler, settingsHandler)
	app := NewApp(engine, db)
	return app, nil
}
